before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ignore:
      - goos == windows && goarch == arm64
    binary: drivio
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.CommitHash={{.Commit}}
      - -X main.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - Merge pull request
      - Merge branch

brews:
  - name: drivio
    homepage: "https://github.com/yourusername/drivio"
    description: "CLI tool for production environment updates"
    repository:
      owner: yourusername
      name: homebrew-tap
    commit_author:
      name: Drivio Bot
      email: bot@drivio.com
    folder: Formula
    goarm: "6"
    test: |
      system "#{bin}/drivio", "--version"
    install: |
      bin.install "drivio"
      bash_completion.install "completions/drivio.bash" => "drivio"
      zsh_completion.install "completions/_drivio" => "_drivio"
      fish_completion.install "completions/drivio.fish"

dockers:
  - image_templates:
      - "yourusername/drivio:{{ .Version }}"
      - "yourusername/drivio:v{{ .Major }}.{{ .Minor }}"
      - "yourusername/drivio:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--platform=linux/arm64"

release:
  draft: false
  prerelease: false
  name_template: '{{ .ProjectName }} {{ .Version }}'
  footer: |
    ## Installation

    ### Using Homebrew (macOS and Linux)
    ```bash
    brew install yourusername/tap/drivio
    ```

    ### Manual installation
    1. Download the binary for your platform from the assets below
    2. Extract the archive
    3. Move the binary to a directory in your PATH

    ### Docker
    ```bash
    docker pull yourusername/drivio:latest
    ```

signs:
  - artifacts: checksum
    signature: "${artifact}.asc"
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

announce:
  twitter:
    enabled: true
    message_template: |
      🚀 {{ .ProjectName }} {{ .Version }} is out! {{ .ReleaseURL }}

      {{- range .Changes.Additions -}}
      ✨ {{ . }}
      {{- end -}}

      {{- range .Changes.Changes -}}
      🔄 {{ . }}
      {{- end -}}

      {{- range .Changes.Removals -}}
      🗑️ {{ . }}
      {{- end -}}